language: python
python:
    - "3.5"
    - "3.7"
    - "3.8"
install:
    - pip install -r requirements-test.txt
services:
    - redis-server
script:
    - python -m unittest discover
notifications:
      slack: measureofquality:JM7OHL9I5dCpVjelhBYiZ1iH
